language: cpp

compiler:
  - clang
  - gcc
  
sudo: required

addons:
  apt:
    packages:
    - cmake
    - clang
    - gcc
  
script:
  - git submodule init
  - mkdir build
  - cd build
  - cmake .. -G Unix\ Makefiles
  - make all
  - make test
