language: cpp

compiler:
  - clang
  - gcc

sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install cmake clang gcc

script:
  - git submodule init
  - mkdir build
  - cd build
  - cmake .. -G Unix\ Makefiles
  - make all
  - make test
