language: cpp

compiler:
  - clang
  - gcc
  
install:
  - apt-get update
  - apt-get upgrade cmake gcc clang
  
script:
  - git submodule init
  - mkdir build
  - cd build
  - cmake .. -G Unix\ Makefiles
  - make all
  - make test
